# Generated by Django 4.2 on 2023-05-01 18:00

import core.marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=core.marketplace.models.marketplace_directory_path),
        ),
    ]
