# Generated by Django 4.2 on 2023-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('web_apps', 'Aplicaciones web'), ('mobile_apps', 'Aplicaciones móviles'), ('games', 'Juegos'), ('cloud_services', 'Servicios en la nube'), ('desktop_software', 'Software de escritorio'), ('dev_tools', 'Herramientas de desarrollo')], default='web_apps', max_length=20),
        ),
    ]
