# Generated by Django 4.2 on 2023-05-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_buy_categoria_buy_precio_alter_buy_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_category', to='marketplace.product'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_price', to='marketplace.product'),
        ),
    ]
