# Generated by Django 4.2 on 2023-05-21 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_buy_categoria_alter_buy_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='categoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_as_category', to='marketplace.product'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='precio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_as_price', to='marketplace.product'),
        ),
    ]
