# Generated by Django 4.2 on 2023-05-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('web_apps', 'Aplicaciones web'), ('mobile_apps', 'Aplicaciones móviles'), ('games', 'Juegos'), ('cloud_services', 'Servicios en la nube'), ('desktop_software', 'Software de escritorio'), ('dev_tools', 'Herramientas de desarrollo')], default='web_apps', max_length=20),
        ),
    ]
