# Generated by Django 4.2 on 2023-05-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=100, null=True),
        ),
    ]
