# Generated by Django 4.2 on 2023-05-23 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0014_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='usuario',
        ),
        migrations.AddField(
            model_name='buy',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buy',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buy',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=100, null=True),
        ),
    ]
